"""
Generate a self-contained Fabric notebook payload (nb_payload.json).
Called by the promote-with-schema-validation workflow.

Env vars (all optional — falls back to static registry):
  SCHEMA_FILE    Path to schema_discovery.json from discover_fabric_schema.py
  LAKEHOUSE_ID   Target lakehouse GUID  (needed for spark.sql() context)
  WORKSPACE_ID   Target workspace GUID  (needed for spark.sql() context)
  OUT_PATH       Output file path       (default: /tmp/nb_payload.json)

Output:
    nb_payload.json — ready to POST to Fabric items API
"""
import json
import base64
import os

SCHEMA_FILE  = os.environ.get("SCHEMA_FILE", "")
LAKEHOUSE_ID = os.environ.get("LAKEHOUSE_ID", "")
WORKSPACE_ID = os.environ.get("WORKSPACE_ID", "")
OUT_PATH     = os.environ.get("OUT_PATH", "/tmp/nb_payload.json")

# ── Load schema ────────────────────────────────────────────────────────────────
if SCHEMA_FILE and os.path.isfile(SCHEMA_FILE):
    # Dynamic schema discovered from live Dev workspace
    disc = json.load(open(SCHEMA_FILE))
    SCHEMA_VERSION = f"live-{disc.get('workspace_id','')[:8]}"
    SCHEMAS = {}
    for table_name, tdata in disc.get("tables", {}).items():
        SCHEMAS[table_name] = {"columns": tdata["columns"]}
    print(f"📂 Schema source   : {SCHEMA_FILE} (live discovery)")
else:
    # Fallback: static schema registry
    repo_root = os.path.join(os.path.dirname(__file__), "..")
    registry_path = os.path.join(repo_root, "notebooks", "00_schema_registry.py")
    ns = {}
    exec(open(registry_path).read(), ns)
    SCHEMA_VERSION = ns["SCHEMA_VERSION"]
    SCHEMAS = ns["SCHEMAS"]
    print(f"📂 Schema source   : 00_schema_registry.py (static fallback)")

# ── Build PySpark DDL code ─────────────────────────────────────────────────────
lines = [
    "# Auto-generated by GitHub Actions — Digital Realty Schema Enforcement",
    f"# Schema source: {'live discovery' if SCHEMA_FILE else 'static registry'} / v{SCHEMA_VERSION}",
    "SCHEMAS = " + repr(SCHEMAS),
    "",
    "created, skipped = [], []",
    "for table_name, schema_def in SCHEMAS.items():",
    "    col_defs = ', '.join([f'`{c[0]}` {c[1]}' for c in schema_def['columns']])",
    "    try:",
    "        spark.sql(f'CREATE TABLE IF NOT EXISTS {table_name} ({col_defs}) USING DELTA')",
    "        created.append(table_name)",
    "        print(f'OK: {table_name}')",
    "    except Exception as e:",
    "        print(f'SKIP: {table_name}: {e}')",
    "        skipped.append(table_name)",
    "",
    f"print('Schema enforcement complete  ({len(SCHEMAS)} tables)')",
    "print(f'Created/verified : {{len(created)}} tables')",
    "if skipped: print(f'Skipped          : {{skipped}}')",
]

inner_code = "\n".join(lines)

# ── Notebook metadata — attach lakehouse so spark.sql() works ─────────────────
nb_metadata = {
    "kernelspec": {
        "display_name": "Synapse PySpark",
        "language": "Python",
        "name": "synapse_pyspark",
    },
    "language_info": {"name": "python"},
}

if LAKEHOUSE_ID and WORKSPACE_ID:
    nb_metadata["trident"] = {
        "lakehouse": {
            "default_lakehouse":              LAKEHOUSE_ID,
            "default_lakehouse_workspace_id": WORKSPACE_ID,
            "known_lakehouses": [{"id": LAKEHOUSE_ID}],
        }
    }
    print(f"🔗 Lakehouse attached : {LAKEHOUSE_ID}")
else:
    print("⚠️  No LAKEHOUSE_ID/WORKSPACE_ID — spark.sql() may fail without default lakehouse")

notebook = {
    "nbformat": 4,
    "nbformat_minor": 4,
    "metadata": nb_metadata,
    "cells": [
        {
            "cell_type": "code",
            "metadata": {},
            "source": inner_code,
            "outputs": [],
            "execution_count": None,
        }
    ],
}

# ── Write payload ──────────────────────────────────────────────────────────────
payload = {
    "displayName": "00_apply_schema",
    "type": "Notebook",
    "definition": {
        "format": "ipynb",
        "parts": [
            {
                "path": "artifact.content.ipynb",
                "payload": base64.b64encode(json.dumps(notebook).encode()).decode(),
                "payloadType": "InlineBase64",
            }
        ],
    },
}

with open(OUT_PATH, "w") as f:
    json.dump(payload, f)

print(f"✅ Notebook payload  → {OUT_PATH}")
print(f"   Tables: {len(SCHEMAS)}")
for t in SCHEMAS:
    print(f"   CREATE TABLE IF NOT EXISTS {t}  ({len(SCHEMAS[t]['columns'])} columns)")
