"""
Generate a self-contained Fabric notebook payload (nb_payload.json) from
the schema registry. Called by the promote-with-schema-validation workflow.

Usage:
    python3 scripts/gen_nb_payload.py
Output:
    /tmp/nb_payload.json  — ready to POST to Fabric items API
"""
import json
import base64
import sys
import os

# Load schema registry from repo root
repo_root = os.path.join(os.path.dirname(__file__), "..")
registry_path = os.path.join(repo_root, "notebooks", "00_schema_registry.py")

ns = {}
exec(open(registry_path).read(), ns)
SCHEMA_VERSION = ns["SCHEMA_VERSION"]
SCHEMAS = ns["SCHEMAS"]

# Build PySpark notebook code that creates tables via CREATE TABLE IF NOT EXISTS
lines = [
    "# Auto-generated by GitHub Actions - Digital Realty Schema Enforcement",
    "# Schema Version: " + SCHEMA_VERSION,
    "SCHEMAS = " + repr(SCHEMAS),
    "",
    "created, skipped = [], []",
    "for table_name, schema_def in SCHEMAS.items():",
    "    col_defs = ', '.join([f'`{name}` {dtype}' for name, dtype, nullable in schema_def['columns']])",
    "    try:",
    "        spark.sql(f'CREATE TABLE IF NOT EXISTS {table_name} ({col_defs}) USING DELTA')",
    "        created.append(table_name)",
    "        print(f'OK: {table_name}')",
    "    except Exception as e:",
    "        print(f'SKIP: {table_name}: {e}')",
    "        skipped.append(table_name)",
    "",
    "print('Schema enforcement complete - v" + SCHEMA_VERSION + "')",
    "print(f'Created/verified: {len(created)} tables')",
    "if skipped: print(f'Skipped: {skipped}')",
]

inner_code = "\n".join(lines)

notebook = {
    "nbformat": 4,
    "nbformat_minor": 4,
    "metadata": {
        "kernelspec": {
            "display_name": "Synapse PySpark",
            "language": "Python",
            "name": "synapse_pyspark",
        },
        "language_info": {"name": "python"},
    },
    "cells": [
        {
            "cell_type": "code",
            "metadata": {},
            "source": inner_code,
            "outputs": [],
            "execution_count": None,
        }
    ],
}

payload = {
    "displayName": "00_apply_schema",
    "type": "Notebook",
    "definition": {
        "format": "ipynb",
        "parts": [
            {
                "path": "artifact.content.ipynb",
                "payload": base64.b64encode(json.dumps(notebook).encode()).decode(),
                "payloadType": "InlineBase64",
            }
        ],
    },
}

out_path = "/tmp/nb_payload.json"
with open(out_path, "w") as f:
    json.dump(payload, f)

print(f"Notebook payload generated → {out_path}")
print(f"  Schema version : {SCHEMA_VERSION}")
print(f"  Tables         : {len(SCHEMAS)}")
for t in SCHEMAS:
    print(f"    CREATE TABLE IF NOT EXISTS {t}  ({len(SCHEMAS[t]['columns'])} columns)")
